name: tmspnn_com
version: "3.8"
services:
  gateway:
    image: openresty/openresty:alpine-fat
    network_mode: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/templates
      - ./certs:/etc/nginx/ssl
      - ./web/dist:/srv/www/static
      - ./resty:/resty_app
    environment:
      - OSS_SECRET_KEY=/run/secrets/oss_secret_key
      - OSS_ACCESS_KEY=/run/secrets/oss_access_key
      - OSS_AUTH_KEY=/run/secrets/oss_auth_key
      - PG_HOST=127.0.0.1:5432
      - PG_USER=/run/secrets/pg_username
      - PG_PASSWORD=/run/secrets/pg_password
      - PG_DATABASE=/run/secrets/pg_database
      - REDIS_HOST=127.0.0.1:6379
    deploy:
        mode: global
        restart_policy:
          condition: on-failure
          delay: 2s
          max_attempts: 3
          window: 10s

  postgresql-master:
    image: "bitnami/postgresql:latest"
    network_mode: "host"
    ports:
      - "5432:5432"
    volumes:
      - /mnt/sdc/pg/master_data:/bitnami/postgresql
    user: root
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=/run/secrets/pg_repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=/run/secrets/pg_repl_password
      - POSTGRESQL_USERNAME=/run/secrets/pg_username
      - POSTGRESQL_PASSWORD=/run/secrets/pg_password
      - POSTGRESQL_DATABASE=/run/secrets/pg_database
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 10s
  
  postgresql-slave:
    image: "bitnami/postgresql:latest"
    network_mode: "host"
    ports:
      - "5433:5432"
    volumes:
      - /mnt/sdc/pg/slave_data:/bitnami/postgresql
    user: root
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=/run/secrets/pg_repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=/run/secrets/pg_repl_password
      - POSTGRESQL_MASTER_HOST=127.0.0.1
      - POSTGRESQL_PASSWORD=/run/secrets/pg_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 1
    
secrets:
  oss_secret_key:
    file: ./secrets/oss_secret_key.txt
  oss_access_key:
    file: ./secrets/oss_access_key.txt
  oss_auth_key:
    file: ./secrets/oss_auth_key.txt
  pg_repl_user:
    file: ./secrets/pg_repl_user.txt
  pg_repl_password:
    file: ./secrets/pg_repl_password.txt
  pg_username:
    file: ./secrets/pg_username.txt
  pg_password:
    file: ./secrets/pg_password.txt
  pg_database:
    file: ./secrets/pg_database.txt
