name: tmspnn
services:
  openresty:
    image: openresty/openresty:alpine-fat
    network_mode: "host"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./certs:/usr/local/openresty/nginx/ssl
      - ./web/dist:/srv/www/static
      - ./resty:/resty_app
    secrets:
      - oss_access_key
      - oss_secret_key
      - oss_auth_key
      - redis_password
    command: bash -c "
      export OSS_ACCESS_KEY=$(cat /run/secrets/oss_access_key)
      && export OSS_SECRET_KEY=$(cat /run/secrets/oss_secret_key)
      && export OSS_AUTH_KEY=$(cat /run/secrets/oss_auth_key)
      && export REDIS_PASSWORD=$(cat /run/secrets/redis_password)
      && luarocks install lapis CRYPTO_DIR=/usr/local/openresty/openssl OPENSSL_DIR=/usr/local/openresty/openssl
      && luarocks install penlight
      && openresty -g 'daemon off;'
      "
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 10s

  postgresql-primary:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    volumes:
      - /mnt/sdc/pg/conf/pg_hba.conf:/bitnami/postgresql/conf/pg_hba.conf
      - /mnt/sdc/pg/primary_data:/bitnami/postgresql
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: replica_user
      POSTGRESQL_REPLICATION_PASSWORD_FILE: /run/secrets/pg_repl_password
      POSTGRESQL_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRESQL_USERNAME: tms
      POSTGRESQL_DATABASE: tmspnn
    secrets:
      - pg_password
      - pg_repl_password
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 2
        window: 8s
  
  postgresql-replica:
    image: bitnami/postgresql:latest
    ports:
      - "5432"
    volumes:
      - /mnt/sdc/pg/conf/pg_hba_replica.conf:/bitnami/postgresql/conf/pg_hba.conf
      - /mnt/sdc/pg/replica_data:/bitnami/postgresql
    depends_on:
      - postgresql-primary
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: replica_user
      POSTGRESQL_REPLICATION_PASSWORD_FILE: /run/secrets/pg_repl_password
      POSTGRESQL_MASTER_HOST: postgresql-primary
      POSTGRESQL_PASSWORD_FILE: /run/secrets/pg_password
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
    secrets:
      - pg_password
      - pg_repl_password
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s
        max_attempts: 2
        window: 8s

  redis-primary:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /mnt/sdc/redis/persistence:/bitnami/redis
    environment:
      REDIS_REPLICATION_MODE: master
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - redis_password

  redis-replica:
    image: bitnami/redis:latest
    ports:
      - "6379"
    depends_on:
      - redis-primary
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-primary
      REDIS_MASTER_PORT_NUMBER: 6379
      REDIS_MASTER_PASSWORD_FILE: /run/secrets/redis_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_repl_password
    secrets:
      - redis_password
      - redis_repl_password
 
secrets:
  oss_secret_key:
    file: ./secrets/oss_secret_key.txt
  oss_access_key:
    file: ./secrets/oss_access_key.txt
  oss_auth_key:
    file: ./secrets/oss_auth_key.txt
  pg_repl_password:
    file: ./secrets/pg_repl_password.txt
  pg_password:
    file: ./secrets/pg_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  redis_repl_password:
    file: ./secrets/redis_repl_password.txt
