name: tmspnn_com

# Ports 5432... Postgres
# Port 6379... Redis
# Ports 8000... OpenResty services
# Ports 9000... Python services
# Ports 10000... Node.js services
# Ports 11000... C/C++ services

services:
  # The Nginx server for load balancing and serving static files
  ngx:
    image: nginx:alpine
    # network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ngx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - ./ngx/well_known.conf:/etc/nginx/well_known.conf
      - ./ngx/cert:/etc/nginx/cert
      - ./static:/srv/www
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      - RESTY_HOST=${RESTY_HOST}
    deploy:
      mode: global
    restart: always

  # OpenResty servers
  resty:
    image: openresty/openresty:alpine-fat
    command: sh -c "
      apk add openssl-dev &&
      luarocks install lapis &&
      /usr/local/openresty/bin/openresty -g 'daemon off;'
      "
    ports:
      - 8000:80
    volumes:
      - ./resty/conf/tmspnn_com.conf:/usr/local/openresty/nginx/conf/nginx.conf
      - ./resty:/opt/resty
    restart: "always"
    environment:
      - PG_HOST=${PG_HOST}

  #  rds:
  #    build:
  #      context: rds
  #    network_mode: "host"
  #    ports:
  #      - 6379:6379
  #    volumes:
  #      - ./rds_persistance:/etc/backup/rds
  #    deploy:
  #      mode: global
  #    restart: always
  #
  #  pg_primary:
  #    build:
  #      context: pg_primary
  #    network_mode: "host"
  #    ports:
  #      - 5432:5432
  #    volumes:
  #      - ./pg_data:/var/lib/postgresql/data
  #    deploy:
  #      mode: global
  #    restart: always
  #
  #  pg_standby:
  #    build:
  #      context: pg_standby
  #    network_mode: "host"
  #    ports:
  #      - 5433:5433
  #      - 5434:5434
  #      - 5435:5435
  #      - 5436:5436
  #    volumes:
  #      - ./pg_data_replica:/var/lib/postgresql/data
  #    deploy:
  #      mode: replicated
  #      replicas: 4
  #    restart: always
  #
  #  lang_processing:
  #    build:
  #      context: lang_processing
  #    ports:
  #      - 9000:9000
  #    deploy:
  #      mode: replicated
  #      replicas: 2
  #    restart: on-failure
  #
  #  py:
  #    build:
  #      context: py_services
  #    ports:
  #      - 9001:9001
  #    deploy:
  #      mode: replicated
  #      replicas: 2
  #    restart: on-failure
  #
  #  nodejs:
  #    build:
  #      context: node_services
  #    ports:
  #      - 9002:9002
  #    deploy:
  #      mode: replicated
  #      replicas: 2
  #    restart: on-failure
